#!/bin/bash

if [ ! -f ./site/.env ]; then
    echo "Error: site/.env does not exist"
    echo "You can create it using cp ./env.docker ./site/.env"

    exit 1
fi

status=$(docker network create --driver bridge coal)

if [ -z "$status" ]; then
    echo 'The network will not be created'
fi

docker volume create --driver local coal

docker build --tag custom:php8.2.5-fpm ./docker/php8.2.5-fpm
docker build --tag custom:mysql5.7.21  ./docker/mysql5.7.21
docker build --tag custom:nginx1.12.1  ./docker/nginx1.12.1
docker build --tag custom:node20.2.0   ./docker/node20.2.0
