#!/bin/fish

source $scriptsDirectory/functions
checkDotEnv

set port 8800

docker run \
  --rm \
  --detach \
  --volume coal:/var/lib/mysql \
  --volume $volumesDirectory/mysql/etc/my.cnf:/etc/my.cnf \
  --net coal \
  --name coal-mysql \
  --add-host=host.docker.internal:host-gateway \
  custom:mysql5.7.21

docker run \
  --volume $projectRoot/site:/site \
  --rm \
  --detach \
  --net coal \
  --name coal-php-fpm \
  --add-host=host.docker.internal:host-gateway \
  --user 1000 \
  custom:php8.2.5-fpm

docker run \
  --rm \
  --detach \
  --volume $projectRoot/site:/site \
  --volume $volumesDirectory/nginx/var/log/nginx:/var/log/nginx \
  --volume $volumesDirectory/nginx/etc/nginx:/etc/nginx \
  --net coal \
  --name coal-nginx \
  --add-host=host.docker.internal:host-gateway \
  --publish $port:8080 \
  custom:nginx1.12.1

echo
echo "Published port: $port"
